@echo off
echo Starting all scripts in the 'scripts' folder...

echo Running pool_create...
node pool_create.cjs
echo Running pool_add_liquidity...
node pool_add_liquidity.cjs
echo Running pool_swap...
node pool_swap.cjs
echo Running pool_remove_liquidity...
node pool_remove_liquidity.cjs
echo Running pool_swap_back_and_forth...
node pool_swap_back_and_forth.cjs

echo All scripts have been executed.
cd ..
pause 