@echo off
echo Starting all scripts in the 'scripts' folder...

echo Running token_create.cjs...
node token_create.cjs
echo Running token_transfer.cjs...
node token_transfer.cjs
echo Running token_update.cjs...
node token_update.cjs
echo Running token_mint.cjs...
node token_mint.cjs
echo Running pool_remove_liquidity.cjs...
node pool_remove_liquidity.cjs
echo Running pool_swap.cjs...
node pool_swap.cjs
echo Running pool_add_liquidity.cjs...
node pool_add_liquidity.cjs
echo Running pool_create.cjs...
node pool_create.cjs
echo Running nft_transfer.cjs...
node nft_transfer.cjs
echo Running nft_update_metadata.cjs...
node nft_update_metadata.cjs
echo Running nft_delist_item.cjs...
node nft_delist_item.cjs
echo Running nft_list_item.cjs...
node nft_list_item.cjs
echo Running nft_mint.cjs...
node nft_mint.cjs
echo Running nft_buy_item.cjs...
node nft_buy_item.cjs
echo Running nft_create_collection.cjs...
node nft_create_collection.cjs
echo Trading pairs are now automatically created with pools - no separate script needed
echo Running market_place_orders_test.cjs (hybrid trading examples)...
node market_place_orders_test.cjs
echo Running launchpad_launch_token.cjs...
node launchpad_launch_token.cjs
echo Running launchpad_participate_presale.cjs...
node launchpad_participate_presale.cjs
echo Running market_cancel_order.cjs...
node market_cancel_order.cjs
echo Running launchpad_claim_tokens.cjs...
node launchpad_claim_tokens.cjs
echo Running farm_stake.cjs...
node farm_stake.cjs
echo Running farm_unstake.cjs...
node farm_unstake.cjs
echo Running advanced_token_test.cjs...
node advanced_token_test.cjs
echo Running farm_claim_rewards.cjs...
node farm_claim_rewards.cjs
echo Running farm_create.cjs...
node farm_create.cjs
echo Running advanced_nft_test.cjs...
node advanced_nft_test.cjs
echo Running advanced_pool_test.cjs...
node advanced_pool_test.cjs
echo Running advanced_launchpad_test.cjs...
node advanced_launchpad_test.cjs
echo Running advanced_market_test.cjs...
node advanced_market_test.cjs
echo Running advanced_farm_test.cjs...
node advanced_farm_test.cjs


echo All scripts have been executed.
cd ..
pause 