@echo off
echo Starting all scripts in the 'scripts' folder...

echo Running token_create.cjs...
node token_create.cjs
echo Running token_mint.cjs...
node token_mint.cjs
echo Running token_transfer.cjs...
node token_transfer.cjs
echo Running token_update.cjs...
node token_update.cjs
echo Running pool_create.cjs...
node pool_create.cjs
echo Running pool_add_liquidity.cjs...
node pool_add_liquidity.cjs
echo TODO
@REM echo Running pool_swap.cjs...
@REM node pool_swap.cjs
@REM echo Running pool_remove_liquidity.cjs...
@REM node pool_remove_liquidity.cjs
@REM echo Running nft_transfer.cjs...
@REM node nft_transfer.cjs
@REM echo Running nft_update_metadata.cjs...
@REM node nft_update_metadata.cjs
@REM echo Running nft_delist_item.cjs...
@REM node nft_delist_item.cjs
@REM echo Running nft_list_item.cjs...
@REM node nft_list_item.cjs
@REM echo Running nft_mint.cjs...
@REM node nft_mint.cjs
@REM echo Running nft_buy_item.cjs...
@REM node nft_buy_item.cjs
@REM echo Running nft_create_collection.cjs...
@REM node nft_create_collection.cjs
@REM echo Trading pairs are now automatically created with pools - no separate script needed
@REM echo Running market_place_orders_test.cjs (hybrid trading examples)...
@REM node market_place_orders_test.cjs
@REM echo Running launchpad_launch_token.cjs...
@REM node launchpad_launch_token.cjs
@REM echo Running launchpad_participate_presale.cjs...
@REM node launchpad_participate_presale.cjs
@REM echo Running market_cancel_order.cjs...
@REM node market_cancel_order.cjs
@REM echo Running launchpad_claim_tokens.cjs...
@REM node launchpad_claim_tokens.cjs
@REM echo Running farm_stake.cjs...
@REM node farm_stake.cjs
@REM echo Running farm_unstake.cjs...
@REM node farm_unstake.cjs
@REM echo Running advanced_token_test.cjs...
@REM node advanced_token_test.cjs
@REM echo Running farm_claim_rewards.cjs...
@REM node farm_claim_rewards.cjs
@REM echo Running farm_create.cjs...
@REM node farm_create.cjs
@REM echo Running advanced_nft_test.cjs...
@REM node advanced_nft_test.cjs
@REM echo Running advanced_pool_test.cjs...
@REM node advanced_pool_test.cjs
@REM echo Running advanced_launchpad_test.cjs...
@REM node advanced_launchpad_test.cjs
@REM echo Running advanced_market_test.cjs...
@REM node advanced_market_test.cjs
@REM echo Running advanced_farm_test.cjs...
@REM node advanced_farm_test.cjs


echo All scripts have been executed.
cd ..
pause 