@echo off
echo Starting all scripts in the 'scripts' folder...

echo Running testnet_tokens...
node token_mint_tests_tbd.cjs
echo Running token_create.cjs...
node token_create.cjs
echo Running token_mint.cjs...
node token_mint.cjs
echo Running token_transfer.cjs...
node token_transfer.cjs
echo Running pool_create.cjs...
node pool_create.cjs
echo Running pool_add_liquidity.cjs...
node pool_add_liquidity.cjs
echo Running pool_swap.cjs...
node pool_swap.cjs
echo Running pool_remove_liquidity.cjs...
node pool_remove_liquidity.cjs

echo All scripts have been executed.
cd ..
pause 