@echo off
echo Starting all nft scripts in the 'scripts' folder...


echo Running nft_create_collection.cjs...
node nft_create_collection.cjs
echo Running nft_mint.cjs...
node nft_mint.cjs
echo Running nft_list_item.cjs...
node nft_list_item.cjs
echo Running nft_buy_item.cjs...
node nft_buy_item.cjs
echo Running nft_delist_item.cjs...
node nft_delist_item.cjs
echo Running nft_transfer.cjs...
node nft_transfer.cjs
echo Running nft_update_metadata.cjs...
node nft_update_metadata.cjs


echo All scripts have been executed.
cd ..
pause 