@echo off
echo Starting all launchpad scripts in the 'scripts' folder...

echo Running launchpad_launch_token...

echo Running launchpad_launch_token...
node launchpad_launch_token.cjs

echo Running launchpad_configure_tokenomics...
node launchpad_configure_tokenomics.cjs

echo Running launchpad_configure_presale...
node launchpad_configure_presale.cjs

echo Running launchpad_configure_airdrop...
node launchpad_configure_airdrop.cjs

echo Running launchpad_update_whitelist...
node launchpad_update_whitelist.cjs

echo Running launchpad_update_status...
node launchpad_update_status.cjs

echo Running launchpad_participate_presale...
node launchpad_participate_presale.cjs

echo Running launchpad_finalize_presale...
node launchpad_finalize_presale.cjs

echo Running launchpad_set_main_token...
node launchpad_set_main_token.cjs

echo Running launchpad_claim_tokens...
node launchpad_claim_tokens.cjs

echo Running launchpad_refund_presale (if applicable)...
node launchpad_refund_presale.cjs

echo Running launchpad_update_metadata...
node launchpad_update_metadata.cjs


echo All scripts have been executed.
cd ..
pause 