name: build-node-20

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  node20:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Show Node and NPM version
        run: |
          node --version
          npm --version
      - 
        name: Verify package.json
        run: cat package.json
      -
        name: Build to run test unit
        uses: docker/build-push-action@v4
        with:
          context: .
          file: node-20.dockerfile
          push: false
          tags: test
          no-cache: true
          build-args: |
            NODE_ENV=development
